# checking out the restarted updated old yahoo finance python module
https://github.com/ranaroussi/yfinance
https://towardsdatascience.com/best-5-free-stock-market-apis-in-2019-ad91dddec984

In [1]:
import yfinance as yf
import pandas as pd
import pickle
from collections import defaultdict
# methods = info

In [2]:
equity = yf.Ticker("lulu")
print("goofball")

goofball

### model of dictionary we want to create

In [3]:
stocks = ['bhp','main','jpm','wfc','jnj','wmt','amzn','msft','vlo','arcc','nke','dis','lulu','cvx']

In [4]:
investment = {}
for stock in stocks:
    equity = yf.Ticker(stock)
    stock = {"price":equity.info['previousClose'], 
             "200DA":equity.info['twoHundredDayAverage'], 
             "Value":equity.info['enterpriseValue'],
             "50DA":equity.info['fiftyDayAverage'],
             "52WH":equity.info['fiftyTwoWeekHigh'],
             "52WL":equity.info["fiftyTwoWeekLow"]
             
            }
    investment[equity.info["symbol"]]=stock

In [5]:
investment

{'BHP': {'price': 55.19,
  '200DA': 51.92123,
  'Value': 154267598848,
  '50DA': 51.112354,
  '52WH': 59.02,
  '52WL': 45.97},
 'MAIN': {'price': 43.57,
  '200DA': 42.39761,
  'Value': 3771120128,
  '50DA': 42.914707,
  '52WH': 44.35,
  '52WL': 31.95},
 'JPM': {'price': 137.34,
  '200DA': 117.569496,
  'Value': 166486884352,
  '50DA': 130.67117,
  '52WH': 138.83,
  '52WL': 91.11},
 'WFC': {'price': 54.22,
  '200DA': 48.815506,
  'Value': 249344229376,
  '50DA': 53.489117,
  '52WH': 54.75,
  '52WL': 43.02},
 'JNJ': {'price': 141.79,
  '200DA': 133.60855,
  'Value': 385438187520,
  '50DA': 135.25412,
  '52WH': 144.98,
  '52WL': 121},
 'WMT': {'price': 120.54,
  '200DA': 114.63333,
  'Value': 415942770688,
  '50DA': 119.13794,
  '52WH': 125.38,
  '52WL': 85.78},
 'AMZN': {'price': 1769.21,
  '200DA': 1817.5559,
  'Value': 904259174400,
  '50DA': 1768.9877,
  '52WH': 2035.8,
  '52WL': 1307},
 'MSFT': {'price': 155.53,
  '200DA': 139.54295,
  'Value': 1135469133824,
  '50DA': 148.70828,
  '52WH': 155.9,
  '52WL': 93.96},
 'VLO': {'price': 95.14,
  '200DA': 85.61768,
  'Value': 48288501760,
  '50DA': 97.6797,
  '52WH': 101.99,
  '52WL': 68.81},
 'ARCC': {'price': 18.54,
  '200DA': 18.45115,
  'Value': 14423569408,
  '50DA': 18.654858,
  '52WH': 19.28,
  '52WL': 14.5},
 'NKE': {'price': 98.81,
  '200DA': 88.08971,
  'Value': 155801092096,
  '50DA': 92.725586,
  '52WH': 100.17,
  '52WL': 66.53},
 'DIS': {'price': 148.46,
  '200DA': 138.26666,
  'Value': 323127050240,
  '50DA': 142.76059,
  '52WH': 153.41,
  '52WL': 100.35},
 'LULU': {'price': 225.35,
  '200DA': 194.40834,
  'Value': 29471115264,
  '50DA': 216.17743,
  '52WH': 235.5,
  '52WL': 110.71},
 'CVX': {'price': 119.36,
  '200DA': 119.87978,
  'Value': 249259278336,
  '50DA': 118.57265,
  '52WH': 127.34,
  '52WL': 100.22}}

In [6]:
pd.DataFrame(investment).T

        price        200DA         Value         50DA     52WH     52WL
BHP     55.19    51.921230  1.542676e+11    51.112354    59.02    45.97
MAIN    43.57    42.397610  3.771120e+09    42.914707    44.35    31.95
JPM    137.34   117.569496  1.664869e+11   130.671170   138.83    91.11
WFC     54.22    48.815506  2.493442e+11    53.489117    54.75    43.02
JNJ    141.79   133.608550  3.854382e+11   135.254120   144.98   121.00
WMT    120.54   114.633330  4.159428e+11   119.137940   125.38    85.78
AMZN  1769.21  1817.555900  9.042592e+11  1768.987700  2035.80  1307.00
MSFT   155.53   139.542950  1.135469e+12   148.708280   155.90    93.96
VLO     95.14    85.617680  4.828850e+10    97.679700   101.99    68.81
ARCC    18.54    18.451150  1.442357e+10    18.654858    19.28    14.50
NKE     98.81    88.089710  1.558011e+11    92.725586   100.17    66.53
DIS    148.46   138.266660  3.231271e+11   142.760590   153.41   100.35
LULU   225.35   194.408340  2.947112e+10   216.177430   235.50   110.71
CVX    119.36   119.879780  2.492593e+11   118.572650   127.34   100.22

In [7]:
class Investment():
    def __init__(self, symbol):
        self.symbol = symbol
        self.equity = yf.Ticker(self.symbol)
        self.grab_price = self.equity.info['previousClose']

In [8]:
# import pickle
# for stock in stocks:
#     stock = Investment(stock)
#     price = (stock.grab_price)
#     symbol = stock.symbol
#     print(price)
#     pickling_on = open(f"{symbol}.pickle","wb")
#     pickle.dump(price, pickling_on)
#     pickling_on.close()
#     pickle_off = open(f"{symbol}.pickle","rb")
#     highwater = pickle.load(pickle_off)
#     print(highwater)

In [9]:
# import pickle
# for stock in stocks:
#     stock = Investment(stock)
#     price = (stock.grab_price)
#     symbol = stock.symbol
#     print(symbol)
    
    
#     pickle_off = open("price.pickle","rb")
#     highwater = pickle.load(pickle_off)
#     if price > highwater:
    
#         pickling_on = open("price.pickle","wb")
#         pickle.dump(price, pickling_on)
#         pickling_on.close()
#         print(f"The previous close for {stock.symbol} is {price} the highwater is {highwater}")
#     else:
    
#         pickling_on.close()
#         print(f"The previous close for {stock.symbol} is {price} the highwater is {highwater}")
#         print(f"Last price is {(highwater - price)/highwater:.2%} below the highwater")

In [10]:
# import pickle
# for stock in stocks:
#     stock = Investment(stock)
#     price = stock.grab_price
#     symbol = stock.symbol
    
#     pickle_off = open(f"{symbol}.pickle","rb")
#     highwater = pickle.load(pickle_off)
#     if price > highwater:
    
#         pickling_on = open(f"{symbol}.pickle","wb")
#         pickle.dump(price, pickling_on)
#         pickling_on.close()
#         print(f"The previous close for {stock.symbol} is {price} the highwater is {highwater}")
    
#     else:
    
#         pickling_on.close()
#         print(f"The previous close for {stock.symbol} is {price} the highwater is {highwater}")
#         print(f"Last price is {(highwater - price)/highwater:.2%} below the highwater")
#         print(" ")

In [11]:
# import pickle

# for stock in stocks:
#     stock = Investment(stock)
#     price = stock.grab_price
#     symbol = stock.symbol
#     hw_dict = {}
#     delta_dict = {}
#     upperSymbol = symbol.upper()
#     print(f"This is the upperSymbol {upperSymbol}")
#     print(f"This is the symbol {symbol}")
    
    
    
#     with open(f"{symbol}.pickle","rb") as pickle_off:
#         highwater = pickle.load(pickle_off)
        
        
#         if price > highwater:
    
#             with open(f"{symbol}.pickle","wb") as pickling_on:
#                 pickle.dump(price, pickling_on)
                
            
            
            
#             print(f"The previous close for {stock.symbol} is ${price:,.2f}. The highwater mark is ${highwater:,.2f}")
#             print(" ")
#         else:   
#             print(f"The previous close for {stock.symbol} is ${price:,.2f}. The highwater mark is ${highwater:,.2f}")
#             print(f"Last price is {(highwater - price)/highwater:.2%} below the highwater mark")
#             print(" ")
            
#     hw_dict['HWater'] = highwater
#     investment[upperSymbol].update( hw_dict )
#     delta = (price - highwater) / price
#     delta_dict['% change'] = delta
#     investment[upperSymbol].update(delta_dict)

In [12]:
import pickle

for stock in stocks:
    stock = Investment(stock)
    price = stock.grab_price
    symbol = stock.symbol
    hw_dict = {}
    delta_dict = {}
    upperSymbol = symbol.upper()
    
    try:
        
        with open(f"{symbol}.pickle","rb") as pickle_off:
            highwater = pickle.load(pickle_off)
#     except:
#         print("No file!  Let's create one")
        
    except:
        print(f"No file for {symbol}!  Let's create one")
        with open(f"{symbol}.pickle","wb") as pickling_on:
                pickle.dump(price, pickling_on)
                highwater = price
                
#     except:
#         print("We have a problem creating a new file")
        
        
    if price > highwater:
    
        with open(f"{symbol}.pickle","wb") as pickling_on:
            pickle.dump(price, pickling_on)
                
            
            
            
            print(f"The previous close for {stock.symbol} is ${price:,.2f}. The highwater mark is ${highwater:,.2f}")
            print(" ")
    else:   
        print(f"The previous close for {stock.symbol} is ${price:,.2f}. The highwater mark is ${highwater:,.2f}")
        print(f"Last price is {(highwater - price)/highwater:.2%} below the highwater mark")
        print(" ")
            
    hw_dict['HWater'] = highwater
    investment[upperSymbol].update( hw_dict )
    delta = (price - highwater) / price
    delta_dict['% change'] = delta
    investment[upperSymbol].update(delta_dict)

The previous close for bhp is $55.19. The highwater mark is $55.19
Last price is 0.00% below the highwater mark

The previous close for main is $43.57. The highwater mark is $43.57
Last price is 0.00% below the highwater mark

The previous close for jpm is $137.34. The highwater mark is $138.02
Last price is 0.49% below the highwater mark

The previous close for wfc is $54.22. The highwater mark is $54.36
Last price is 0.26% below the highwater mark

The previous close for jnj is $141.79. The highwater mark is $141.79
Last price is 0.00% below the highwater mark

The previous close for wmt is $120.54. The highwater mark is $120.54
Last price is 0.00% below the highwater mark

The previous close for amzn is $1,769.21. The highwater mark is $1,769.21
Last price is 0.00% below the highwater mark

The previous close for msft is $155.53. The highwater mark is $155.53
Last price is 0.00% below the highwater mark

The previous close for vlo is $95.14. The highwater mark is $95.14
Last price is 0.00% below the highwater mark

The previous close for arcc is $18.54. The highwater mark is $18.85
Last price is 1.64% below the highwater mark

The previous close for nke is $98.81. The highwater mark is $98.81
Last price is 0.00% below the highwater mark

The previous close for dis is $148.46. The highwater mark is $148.46
Last price is 0.00% below the highwater mark

The previous close for lulu is $225.35. The highwater mark is $229.65
Last price is 1.87% below the highwater mark

The previous close for cvx is $119.36. The highwater mark is $119.36
Last price is 0.00% below the highwater mark

In [13]:
hw_dict

{'HWater': 119.36}

In [14]:
investment

{'BHP': {'price': 55.19,
  '200DA': 51.92123,
  'Value': 154267598848,
  '50DA': 51.112354,
  '52WH': 59.02,
  '52WL': 45.97,
  'HWater': 55.19,
  '% change': 0.0},
 'MAIN': {'price': 43.57,
  '200DA': 42.39761,
  'Value': 3771120128,
  '50DA': 42.914707,
  '52WH': 44.35,
  '52WL': 31.95,
  'HWater': 43.57,
  '% change': 0.0},
 'JPM': {'price': 137.34,
  '200DA': 117.569496,
  'Value': 166486884352,
  '50DA': 130.67117,
  '52WH': 138.83,
  '52WL': 91.11,
  'HWater': 138.02,
  '% change': -0.004951215960390322},
 'WFC': {'price': 54.22,
  '200DA': 48.815506,
  'Value': 249344229376,
  '50DA': 53.489117,
  '52WH': 54.75,
  '52WL': 43.02,
  'HWater': 54.36,
  '% change': -0.0025820730357801656},
 'JNJ': {'price': 141.79,
  '200DA': 133.60855,
  'Value': 385438187520,
  '50DA': 135.25412,
  '52WH': 144.98,
  '52WL': 121,
  'HWater': 141.79,
  '% change': 0.0},
 'WMT': {'price': 120.54,
  '200DA': 114.63333,
  'Value': 415942770688,
  '50DA': 119.13794,
  '52WH': 125.38,
  '52WL': 85.78,
  'HWater': 120.54,
  '% change': 0.0},
 'AMZN': {'price': 1769.21,
  '200DA': 1817.5559,
  'Value': 904259174400,
  '50DA': 1768.9877,
  '52WH': 2035.8,
  '52WL': 1307,
  'HWater': 1769.21,
  '% change': 0.0},
 'MSFT': {'price': 155.53,
  '200DA': 139.54295,
  'Value': 1135469133824,
  '50DA': 148.70828,
  '52WH': 155.9,
  '52WL': 93.96,
  'HWater': 155.53,
  '% change': 0.0},
 'VLO': {'price': 95.14,
  '200DA': 85.61768,
  'Value': 48288501760,
  '50DA': 97.6797,
  '52WH': 101.99,
  '52WL': 68.81,
  'HWater': 95.14,
  '% change': 0.0},
 'ARCC': {'price': 18.54,
  '200DA': 18.45115,
  'Value': 14423569408,
  '50DA': 18.654858,
  '52WH': 19.28,
  '52WL': 14.5,
  'HWater': 18.85,
  '% change': -0.016720604099244998},
 'NKE': {'price': 98.81,
  '200DA': 88.08971,
  'Value': 155801092096,
  '50DA': 92.725586,
  '52WH': 100.17,
  '52WL': 66.53,
  'HWater': 98.81,
  '% change': 0.0},
 'DIS': {'price': 148.46,
  '200DA': 138.26666,
  'Value': 323127050240,
  '50DA': 142.76059,
  '52WH': 153.41,
  '52WL': 100.35,
  'HWater': 148.46,
  '% change': 0.0},
 'LULU': {'price': 225.35,
  '200DA': 194.40834,
  'Value': 29471115264,
  '50DA': 216.17743,
  '52WH': 235.5,
  '52WL': 110.71,
  'HWater': 229.65,
  '% change': -0.01908142888839588},
 'CVX': {'price': 119.36,
  '200DA': 119.87978,
  'Value': 249259278336,
  '50DA': 118.57265,
  '52WH': 127.34,
  '52WL': 100.22,
  'HWater': 119.36,
  '% change': 0.0}}

In [15]:
# def write_to_pickle_file(filename, an_object):
#     with open(filename, 'wb') as file:
#         pickle.dump(an_object, file)

In [16]:
# def write_to_pickle_file("stockhighwater.pickle", an_object):
#     with open(filename, 'wb') as file:
#         pickle.dump(an_object, file)

In [17]:
# import pickle
# magic = {1:"A",2:"B",3:"C",4:"D",5:"E"}
# pickling_on = open("Emp.pickle","wb")
# pickle.dump(magic, pickling_on)
# pickling_on.close()

In [18]:
# pickle_off = open("Emp.pickle","rb")
# magic = pickle.load(pickle_off)
# print(magic)

In [19]:
pd.DataFrame(investment)

,BHP,MAIN,JPM,WFC,JNJ,WMT,AMZN,MSFT,VLO,ARCC,NKE,DIS,LULU,CVX
price,5.519000e+01,4.357000e+01,1.373400e+02,5.422000e+01,1.417900e+02,1.205400e+02,1.769210e+03,1.555300e+02,9.514000e+01,1.854000e+01,9.881000e+01,1.484600e+02,2.253500e+02,1.193600e+02
200DA,5.192123e+01,4.239761e+01,1.175695e+02,4.881551e+01,1.336086e+02,1.146333e+02,1.817556e+03,1.395429e+02,8.561768e+01,1.845115e+01,8.808971e+01,1.382667e+02,1.944083e+02,1.198798e+02
Value,1.542676e+11,3.771120e+09,1.664869e+11,2.493442e+11,3.854382e+11,4.159428e+11,9.042592e+11,1.135469e+12,4.828850e+10,1.442357e+10,1.558011e+11,3.231271e+11,2.947112e+10,2.492593e+11
50DA,5.111235e+01,4.291471e+01,1.306712e+02,5.348912e+01,1.352541e+02,1.191379e+02,1.768988e+03,1.487083e+02,9.767970e+01,1.865486e+01,9.272559e+01,1.427606e+02,2.161774e+02,1.185726e+02
52WH,5.902000e+01,4.435000e+01,1.388300e+02,5.475000e+01,1.449800e+02,1.253800e+02,2.035800e+03,1.559000e+02,1.019900e+02,1.928000e+01,1.001700e+02,1.534100e+02,2.355000e+02,1.273400e+02
52WL,4.597000e+01,3.195000e+01,9.111000e+01,4.302000e+01,1.210000e+02,8.578000e+01,1.307000e+03,9.396000e+01,6.881000e+01,1.450000e+01,6.653000e+01,1.003500e+02,1.107100e+02,1.002200e+02
HWater,5.519000e+01,4.357000e+01,1.380200e+02,5.436000e+01,1.417900e+02,1.205400e+02,1.769210e+03,1.555300e+02,9.514000e+01,1.885000e+01,9.881000e+01,1.484600e+02,2.296500e+02,1.193600e+02
% change,0.000000e+00,0.000000e+00,-4.951216e-03,-2.582073e-03,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,-1.672060e-02,0.000000e+00,0.000000e+00,-1.908143e-02,0.000000e+00

In [20]:
investment

{'BHP': {'price': 55.19,
  '200DA': 51.92123,
  'Value': 154267598848,
  '50DA': 51.112354,
  '52WH': 59.02,
  '52WL': 45.97,
  'HWater': 55.19,
  '% change': 0.0},
 'MAIN': {'price': 43.57,
  '200DA': 42.39761,
  'Value': 3771120128,
  '50DA': 42.914707,
  '52WH': 44.35,
  '52WL': 31.95,
  'HWater': 43.57,
  '% change': 0.0},
 'JPM': {'price': 137.34,
  '200DA': 117.569496,
  'Value': 166486884352,
  '50DA': 130.67117,
  '52WH': 138.83,
  '52WL': 91.11,
  'HWater': 138.02,
  '% change': -0.004951215960390322},
 'WFC': {'price': 54.22,
  '200DA': 48.815506,
  'Value': 249344229376,
  '50DA': 53.489117,
  '52WH': 54.75,
  '52WL': 43.02,
  'HWater': 54.36,
  '% change': -0.0025820730357801656},
 'JNJ': {'price': 141.79,
  '200DA': 133.60855,
  'Value': 385438187520,
  '50DA': 135.25412,
  '52WH': 144.98,
  '52WL': 121,
  'HWater': 141.79,
  '% change': 0.0},
 'WMT': {'price': 120.54,
  '200DA': 114.63333,
  'Value': 415942770688,
  '50DA': 119.13794,
  '52WH': 125.38,
  '52WL': 85.78,
  'HWater': 120.54,
  '% change': 0.0},
 'AMZN': {'price': 1769.21,
  '200DA': 1817.5559,
  'Value': 904259174400,
  '50DA': 1768.9877,
  '52WH': 2035.8,
  '52WL': 1307,
  'HWater': 1769.21,
  '% change': 0.0},
 'MSFT': {'price': 155.53,
  '200DA': 139.54295,
  'Value': 1135469133824,
  '50DA': 148.70828,
  '52WH': 155.9,
  '52WL': 93.96,
  'HWater': 155.53,
  '% change': 0.0},
 'VLO': {'price': 95.14,
  '200DA': 85.61768,
  'Value': 48288501760,
  '50DA': 97.6797,
  '52WH': 101.99,
  '52WL': 68.81,
  'HWater': 95.14,
  '% change': 0.0},
 'ARCC': {'price': 18.54,
  '200DA': 18.45115,
  'Value': 14423569408,
  '50DA': 18.654858,
  '52WH': 19.28,
  '52WL': 14.5,
  'HWater': 18.85,
  '% change': -0.016720604099244998},
 'NKE': {'price': 98.81,
  '200DA': 88.08971,
  'Value': 155801092096,
  '50DA': 92.725586,
  '52WH': 100.17,
  '52WL': 66.53,
  'HWater': 98.81,
  '% change': 0.0},
 'DIS': {'price': 148.46,
  '200DA': 138.26666,
  'Value': 323127050240,
  '50DA': 142.76059,
  '52WH': 153.41,
  '52WL': 100.35,
  'HWater': 148.46,
  '% change': 0.0},
 'LULU': {'price': 225.35,
  '200DA': 194.40834,
  'Value': 29471115264,
  '50DA': 216.17743,
  '52WH': 235.5,
  '52WL': 110.71,
  'HWater': 229.65,
  '% change': -0.01908142888839588},
 'CVX': {'price': 119.36,
  '200DA': 119.87978,
  'Value': 249259278336,
  '50DA': 118.57265,
  '52WH': 127.34,
  '52WL': 100.22,
  'HWater': 119.36,
  '% change': 0.0}}

In [21]:
investment["BHP"]

{'price': 55.19,
 '200DA': 51.92123,
 'Value': 154267598848,
 '50DA': 51.112354,
 '52WH': 59.02,
 '52WL': 45.97,
 'HWater': 55.19,
 '% change': 0.0}

In [22]:
update_investment = defaultdict()
update_investment['symbol']['HW'] = highwater

KeyError: 'symbol'

In [ ]:
from collections import defaultdict
my_dict = defaultdict(dict)
my_dict['myKey']['nestedDictKey1'] = a_value
my_dict['myKey']['nestedDictKey2'] = another_value

from collections import defaultdict
my_dict = defaultdict(dict)
my_dict['myKey']['nestedDictKey1'] = a_value
my_dict['myKey']['nestedDictKey2'] = another_value